spring.application.name=authService
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=localAniketPostgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=my-secret-jwt-key-for-macrominder-by-aniket

oauth.facebook.id=506401492418349
oauth.facebook.secret=150dc3b481076ccb8571c8e2fd8305ab